dest = "dist"
base = "/finders/"

plugins = [
  [ "@vuepress/back-to-top" ]
]

[themeConfig]
repo = "dxx/finders"
docsRepo = "dxx/finders-docs"
docsDir = "src"

smoothScroll = true

[locales."/"]
lang = "en-US"
title = "Finders"
description = "Distributed service management"

[themeConfig.locales."/"]
selectText = "Languages"
label = "English"
ariaLabel = "Select language"
lastUpdated = "Last Updated"

nav = [
  { text = "Guide", link = "/guide/" },
  { text = "Config", link = "/config/" }
]

[themeConfig.locales."/".sidebar]
"/guide/" = [
  { title = "Guide", collapsable = false, sidebarDepth = 1, children = [
    "",
    "architecture",
    "getting-started",
  ] },
  { title = "Open API", collapsable = false, children = [
    "instance-api"
  ] }
]


[locales."/zh/"]
lang = "zh-CN"
title = "Finders"
description = "分布式服务管理"

[themeConfig.locales."/zh/"]
selectText = "选择语言"
label = "简体中文"
ariaLabel = "选择语言"
lastUpdated = "上次更新"

nav = [
  { text = "指南", link = "/zh/guide/" },
  { text = "配置", link = "/zh/config/" }
]

[themeConfig.locales."/zh/".sidebar]
"/zh/guide/" = [
  { title = "指南", collapsable = false, sidebarDepth = 1, children = [
    "",
    "architecture",
    "getting-started",
  ] },
  { title = "Open API", collapsable = false, children = [
    "instance-api"
  ] }
]
